version: '3.2'
services:
  jupyter-lab:
    build: .
    volumes:
      - type: bind
        source: "./"
        target: "/workspace/"
    working_dir: /workspace
    command: >
      bash -c "jupyter lab --ip=0.0.0.0 --port=8080 --no-browser --NotebookApp.token='' --allow-root"
    ports:
      - "8080:8080"
      - "8082:8082"
